[package]
name = "notify-rust"
version = "3.6.0"
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
description = "Show desktop notifications (linux, bsd, mac). Pure Rust dbus client and server."
homepage = "https://github.com/hoodie/notify-rust"
repository = "https://github.com/hoodie/notify-rust"
documentation = "https://docs.rs/notify-rust/"

license = "MIT/Apache-2.0"
keywords = ["desktop", "notification", "notify", "dbus", "libnotify", "linux", "macos"]
readme = "README.md"

include = [
  "README.md",
  "History.md",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[dependencies]
[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
dbus = "0.6"
lazy_static = {version = "1.1", optional = true}
image = {version = "0.20", optional = true}

[target.'cfg(target_os="macos")'.dependencies]
mac-notification-sys = "0.3"

[features]
default = []
debug_namespace = []
images = ["image", "lazy_static"]
